### ISSUE TITLE
Placing items in the world crashes client and server

### ISSUE THREAD

**Issue by Aesthir** [glisco03/things#106]
Placing an item or loading a chunk that has a placed item crashes the game. This should provide all the information you need to reproduce, but lmk if you need something else:

`Time: 2024-09-02 15:36:58
Description: Chunk save failure

io.wispforest.endec.impl.MissingAttributeValueException: Context did not provide a value for attribute 'registries'
	at io.wispforest.endec.SerializationContext.requireAttributeValue(SerializationContext.java:90)
	at io.wispforest.owo.serialization.CodecUtils.lambda$toEndecWithRegistries$4(CodecUtils.java:102)
	at io.wispforest.endec.Endec$1.encode(Endec.java:136)
	at io.wispforest.endec.Endec.encodeFully(Endec.java:41)
	at net.minecraft.class_2487.put(class_2487.java:2195)
	at io.wispforest.endec.util.MapCarrier.put(MapCarrier.java:34)
	at com.glisco.things.blocks.PlacedItemBlockEntity.method_11007(PlacedItemBlockEntity.java:43)
	at net.minecraft.class_2586.method_38244(class_2586.java:114)
	at net.minecraft.class_2586.method_38242(class_2586.java:94)
	at net.minecraft.class_2818.method_20598(class_2818.java:409)
	at net.minecraft.class_2852.method_12410(class_2852.java:331)
	at net.minecraft.class_3898.method_17228(class_3898.java:784)
	at net.minecraft.class_3898.method_60440(class_3898.java:511)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3898.method_20605(class_3898.java:483)
	at net.minecraft.class_3898.method_17233(class_3898.java:441)
	at net.minecraft.class_3215.method_12127(class_3215.java:314)
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:615)
	at net.minecraft.class_3176.method_3782(class_3176.java:561)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:735)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: IO-Worker-6
Stacktrace:
	at io.wispforest.endec.SerializationContext.requireAttributeValue(SerializationContext.java:90)
	at io.wispforest.owo.serialization.CodecUtils.lambda$toEndecWithRegistries$4(CodecUtils.java:102)
	at io.wispforest.endec.Endec$1.encode(Endec.java:136)
	at io.wispforest.endec.Endec.encodeFully(Endec.java:41)
	at net.minecraft.class_2487.put(class_2487.java:2195)
	at io.wispforest.endec.util.MapCarrier.put(MapCarrier.java:34)
	at com.glisco.things.blocks.PlacedItemBlockEntity.method_11007(PlacedItemBlockEntity.java:43)
	at net.minecraft.class_2586.method_38244(class_2586.java:114)
	at net.minecraft.class_2586.method_38242(class_2586.java:94)
	at net.minecraft.class_2818.method_20598(class_2818.java:409)
	at net.minecraft.class_2852.method_12410(class_2852.java:331)
	at net.minecraft.class_3898.method_17228(class_3898.java:784)
	at net.minecraft.class_3898.method_60440(class_3898.java:511)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3898.method_20605(class_3898.java:483)
	at net.minecraft.class_3898.method_17233(class_3898.java:441)
	at net.minecraft.class_3215.method_12127(class_3215.java:314)
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:615)
`

**Comment by gliscowo** [comment]
Thanks for reporting, this has now been fixed in [0.4.2](https://modrinth.com/mod/things/version/0.4.2+1.21)

Cheers
