### ISSUE TITLE
Displacement Tome make game crash

### ISSUE THREAD

**Issue by BrokenDawn627** [glisco03/things#24]
when I open the Displacement Tome，the game crashed.

> [15:35:46] [Server thread/INFO]: Night_Break取得了进度[量子纠缠]
[15:35:46] [Render thread/INFO]: [CHAT] Night_Break取得了进度[量子纠缠]
[15:35:46] [Render thread/INFO]: Loaded 120 advancements
[15:35:50] [Render thread/WARN]: Reclaimed 481600 bytes at address 2607006921120 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 4480 bytes at address 2606270284240 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 24000 bytes at address 2607054993920 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 3200 bytes at address 2606069422432 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 36120 bytes at address 2605143105504 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 2604 bytes at address 2607015211520 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 1800 bytes at address 2607137547488 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 34720 bytes at address 2606172098928 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 28872 bytes at address 2606044566192 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 336 bytes at address 2607081676192 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 240 bytes at address 2606167128432 that were leaked from an unknown location (logging is disabled)
[15:35:50] [Render thread/WARN]: Reclaimed 384960 bytes at address 2605158187024 that were leaked from an unknown location (logging is disabled)
[15:35:51] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
	at com.glisco.things.items.generic.DisplacementTomeItem.lambda$use$0(DisplacementTomeItem.java:86) ~[things-0.2.13+1.18.jar:?]
	at net.minecraft.class_747.createMenu(class_747.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:1032) ~[client-intermediary.jar:?]
	at com.glisco.things.items.generic.DisplacementTomeItem.method_7836(DisplacementTomeItem.java:85) ~[things-0.2.13+1.18.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1093) ~[client-intermediary.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.wispforest.owo.network.NetworkException: Network handlers may only be registered during mod initialization
	at io.wispforest.owo.network.OwoNetChannel.createSerializer(OwoNetChannel.java:253) ~[owo-lib-0.5.1+1.18.jar:?]
	at io.wispforest.owo.network.OwoNetChannel.registerServerbound(OwoNetChannel.java:146) ~[owo-lib-0.5.1+1.18.jar:?]
	at com.glisco.things.misc.DisplacementTomeScreenHandler.<clinit>(DisplacementTomeScreenHandler.java:106) ~[things-0.2.13+1.18.jar:?]
	... 23 more
[15:35:51] [Server thread/ERROR]: This crash report has been saved to: F:\Infinity-1.18\test\.minecraft\versions\Infinity\crash-reports\crash-2022-01-31_15.35.51-server.txt
[15:35:51] [Server thread/INFO]: Stopping server
[15:35:51] [Server thread/INFO]: Saving players

**Comment by BrokenDawn627** [comment]
version is 0.2.13
