### ISSUE TITLE
Putting on Socks in Trinkets causes "Player Ability" issue

### ISSUE THREAD

**Issue by TheWyzer** [glisco03/things#28]
I updated to 0.2.15+1.18 on 1.18.1 and now my socks that used to work fine throw the following error:
`[Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).`

I made a new set of socks and the error persists.  Speed appears fine, however the "jumpy" is negated.  Any ideas?

Full error code in case there is more relevance,

```
[Server thread/WARN]: Player ability minecraft:mayfly was updated externally (expected disabled, was enabled).
java.lang.RuntimeException: stacktrace
	at io.github.ladysnake.pal.impl.VanillaAbilityTracker.checkConflict(VanillaAbilityTracker.java:72) ~[playerabilitylib-1.5.0-12a50facfa7d1ad5.jar:?]
	at net.minecraft.class_3222.handler$edm000$checkAbilityConsistency(class_3222.java:15307) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_7355(class_3222.java:1287) ~[client-intermediary.jar:?]
	at com.glisco.things.misc.SockDataComponent.modifySpeed(SockDataComponent.java:47) ~[things-0.2.15+1.18.jar:?]
	at com.glisco.things.misc.SockDataComponent.updateSockSpeed(SockDataComponent.java:33) ~[things-0.2.15+1.18.jar:?]
	at com.glisco.things.items.trinkets.SocksItem.tick(SocksItem.java:66) ~[things-0.2.15+1.18.jar:?]
	at net.minecraft.class_1661.mda7ebde$lambda$updateItems$0$2(class_1661.java:6200) ~[client-intermediary.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:335) ~[trinkets-3.2.0.jar:?]
	at net.minecraft.class_1661.mda7ebde$lambda$updateItems$1$1(class_1661.java:6199) ~[client-intermediary.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.class_1661.handler$fdl002$updateItems(class_1661.java:6198) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7381(class_1661.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2349) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:479) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by gliscowo** [comment]
I have not been able to reproduce this error in my own testing, and from the nature of it I would also suspect another mod being at fault. The problem you're seeing in the log is a warning emitted by PlayerAbilityLib if somebofy externally modifies the player's abilities. Things does not do this, however the socks trigger an ability update which then prompts PAL to check for modifications and thus detect what some other mod has done and throw an error. I don't quite get what you mean by jumpy being "inverted", though. If you're simply referring to it not working, remember that is is toggleable. In any case, I would suspect some other mod which somehow grants creative flight being at fault, and it would be very useful if you could investigate that
Cheers

**Comment by TheWyzer** [comment]
The "jumpy" aspect of the Socks is not working, is what I meant by "negated".  Gobber2 Dragon armor provides creative flight.  I restored a backup of the instance before updating Things, as that is when I lost "jumpy" in the socks, however even in the "backup" instance the same error persists.  As a note I can say I had the flight and socks for over 20 hours of game play before this issue.  For some reason the only thing that now allows me to have "jump" is the MC Beacon, the potions for Jump II and such now also throw the same error, not really sure what happened and was hoping you might have had some insight.  Thanks for looking and the response, if I find solution I will try to let you know.
