### ISSUE TITLE
some errors when i run server, can you have a look? 

### ISSUE THREAD

**Issue by tealtoxic** [glisco03/things#48]
hai, i was setting up server and using a modpack that has " things " mod in it and it show some error. can you have a look? thank you!
MC Fabric 1.19.2 / things 0.2.20

`[21.09 09:54:43] [Server] [Worker-Main-2/ERROR]: Couldn't parse data file things:broken_watch from things:recipes/broken_watch.json
[21.09 09:54:43] [Server] com.google.gson.JsonParseExceptionjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:512) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15276(class_3518.java:549) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_20731(class_4309.java:42) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_18789(class_4309.java:17) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21.09 09:54:43] [Server] Caused byjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:510) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	... more
[21.09 09:54:43] [Server] [Worker-Main-2/ERROR]: Couldn't parse data file things:displacement_tome from things:recipes/displacement_tome.json
[21.09 09:54:43] [Server] com.google.gson.JsonParseExceptionjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:512) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15276(class_3518.java:549) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_20731(class_4309.java:42) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_18789(class_4309.java:17) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21.09 09:54:43] [Server] Caused byjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:510) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	... more
[21.09 09:54:43] [Server] [Worker-Main-2/ERROR]: Couldn't parse data file things:hardening_catalyst from things:recipes/hardening_catalyst.json
[21.09 09:54:43] [Server] com.google.gson.JsonParseExceptionjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:512) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15276(class_3518.java:549) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_20731(class_4309.java:42) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_18789(class_4309.java:17) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21.09 09:54:43] [Server] Caused byjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:510) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	... more
[21.09 09:54:43] [Server] [Worker-Main-2/ERROR]: Couldn't parse data file things:infernal_scepter from things:recipes/infernal_scepter.json
[21.09 09:54:43] [Server] com.google.gson.JsonParseExceptionjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:512) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15276(class_3518.java:549) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_20731(class_4309.java:42) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4309.method_18789(class_4309.java:17) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
[21.09 09:54:43] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[21.09 09:54:43] [Server] Caused byjava.io.EOFException: End of input at line 1 column 1 path $
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar:?]
[21.09 09:54:43] [Server] 	at net.minecraft.class_3518.method_15267(class_3518.java:510) ~[server-intermediary.jar:?]
[21.09 09:54:43] [Server] 	... more`

**Comment by gliscowo** [comment]
You're almost certainly not running [0.2.20](https://modrinth.com/mod/things/version/0.2.20%2B1.19), as this recipe problem has been fixed in that version. If this is actually somehow happening in 0.2.20, please tell us where you downloaded that - it really shouldn't contain this recipe anymore
Cheers

**Comment by gliscowo** [comment]
Given that there has been no activity on this issue and the underlying problem is almost certainly fixed, I'll close this. Should you be able to verify that this still happens, please refer to my comment above and reopen this issue
Cheers
